
export const dashboardTutorialSteps = [
  {
    id: 'welcome',
    title: 'Welcome to AstraAI! 🚀',
    description: 'Let\'s take a quick tour of your AI orchestration platform. This tutorial will show you the key features to get you started.',
    target: '[data-tutorial="main-features"]',
    position: 'bottom' as const,
    highlightPadding: 12,
    nextTrigger: 'manual' as const,
  },
  {
    id: 'quick-start',
    title: 'Quick Start Guide',
    description: 'Here\'s your personalized setup checklist. Complete these steps to unlock the full potential of AstraAI.',
    target: '[data-tutorial="quick-start-guide"]',
    position: 'left' as const,
    highlightPadding: 8,
    action: 'hover' as const,
  },
  {
    id: 'quick-actions',
    title: 'Quick Actions Panel',
    description: 'Access frequently used actions instantly. Connect apps, create workflows, and manage your AI engines from here.',
    target: '[data-tutorial="quick-actions"]',
    position: 'left' as const,
    highlightPadding: 8,
  },
  {
    id: 'system-status',
    title: 'System Health Overview',
    description: 'Monitor your AI system\'s performance at a glance. Track uptime, processing speed, and overall health metrics.',
    target: '[data-tutorial="system-overview"]',
    position: 'top' as const,
    highlightPadding: 8,
  },
  {
    id: 'ai-engines',
    title: 'AI Engines Status',
    description: 'View the status of all your AI engines. Each engine handles different types of tasks like NLP, vision, or automation.',
    target: '[data-tutorial="ai-engines"]',
    position: 'top' as const,
    highlightPadding: 8,
  },
  {
    id: 'activity-feed',
    title: 'Live Activity Feed',
    description: 'Stay updated with real-time activity from your AI workflows. Monitor task completions, alerts, and system events.',
    target: '[data-tutorial="activity-feed"]',
    position: 'top' as const,
    highlightPadding: 8,
  },
  {
    id: 'workflow-controls',
    title: 'Workflow Management',
    description: 'Control your automated workflows. Start, pause, or modify workflows to optimize your AI operations.',
    target: '[data-tutorial="workflow-controls"]',
    position: 'left' as const,
    highlightPadding: 8,
  },
  {
    id: 'tabs-navigation',
    title: 'Explore More Features',
    description: 'Use these tabs to access Workflows, Agents, Integrations, Analytics, and Pilot features. Each section offers powerful capabilities.',
    target: '[data-tutorial="dashboard-tabs"]',
    position: 'bottom' as const,
    highlightPadding: 8,
  },
];

export const landingTutorialSteps = [
  {
    id: 'hero-welcome',
    title: 'Welcome to AstraAI',
    description: 'AstraAI is your enterprise-grade AI orchestration platform. Let\'s explore what makes it powerful.',
    target: '[data-tutorial="hero-section"]',
    position: 'bottom' as const,
    highlightPadding: 12,
  },
  {
    id: 'key-features',
    title: 'Key Features',
    description: 'Discover AstraAI\'s core capabilities: AI workflow automation, real-time insights, and seamless integrations.',
    target: '[data-tutorial="features-section"]',
    position: 'top' as const,
    highlightPadding: 8,
  },
  {
    id: 'pricing-plans',
    title: 'Choose Your Plan',
    description: 'Select from our flexible pricing plans designed for teams of all sizes, from startups to enterprise.',
    target: '[data-tutorial="pricing-section"]',
    position: 'top' as const,
    highlightPadding: 8,
  },
  {
    id: 'get-started',
    title: 'Ready to Begin?',
    description: 'Click "Get Started" to access your dashboard and begin your AI orchestration journey.',
    target: '[data-tutorial="cta-section"]',
    position: 'top' as const,
    highlightPadding: 8,
    action: 'click' as const,
  },
];
