// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hiwbmeaiwrusuvtkabyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhpd2JtZWFpd3J1c3V2dGthYnl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODM4ODcsImV4cCI6MjA2NTU1OTg4N30.Np7LGLxtzUs--Cymu9D3zWyToJgpYWqgSEPrGkHCjFI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);